#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$args = $_SERVER['argv'];

if (count($args) > 1) {

} else {
    echo "Let me smith y\' weapons.  I am a smith, such is my purpose.";
}
?>