#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$args = $_SERVER['argv'];

if (count($args) > 1) {

} else {
    echo "Let me smith y\' weapons.  I am a smith, such is my purpose.";
}
?>